// Generated by tools/prep_books.py - do not edit. Texts are embedded via
// board_build.embed_files in platformio.ini; objcopy names the symbols after
// the file path.
#pragma once
#include <stddef.h>
#include <stdint.h>

struct BuiltinBook {
    const char*    title;
    const char*    author;
    const char*    source;
    const char*    blurb;
    const char*    lang;
    uint16_t       year;
    const uint8_t* start;
    const uint8_t* end;
    const uint8_t* coverStart;   // PNG, or nullptr
    const uint8_t* coverEnd;
};

extern "C" const uint8_t _binary_assets_books_alice_txt_start[] asm("_binary_assets_books_alice_txt_start");
extern "C" const uint8_t _binary_assets_books_alice_txt_end[]   asm("_binary_assets_books_alice_txt_end");
extern "C" const uint8_t _binary_assets_covers_alice_png_start[] asm("_binary_assets_covers_alice_png_start");
extern "C" const uint8_t _binary_assets_covers_alice_png_end[]   asm("_binary_assets_covers_alice_png_end");
extern "C" const uint8_t _binary_assets_books_frankenstein_txt_start[] asm("_binary_assets_books_frankenstein_txt_start");
extern "C" const uint8_t _binary_assets_books_frankenstein_txt_end[]   asm("_binary_assets_books_frankenstein_txt_end");
extern "C" const uint8_t _binary_assets_covers_frankenstein_png_start[] asm("_binary_assets_covers_frankenstein_png_start");
extern "C" const uint8_t _binary_assets_covers_frankenstein_png_end[]   asm("_binary_assets_covers_frankenstein_png_end");
extern "C" const uint8_t _binary_assets_books_christmas_carol_txt_start[] asm("_binary_assets_books_christmas_carol_txt_start");
extern "C" const uint8_t _binary_assets_books_christmas_carol_txt_end[]   asm("_binary_assets_books_christmas_carol_txt_end");
extern "C" const uint8_t _binary_assets_covers_christmas_carol_png_start[] asm("_binary_assets_covers_christmas_carol_png_start");
extern "C" const uint8_t _binary_assets_covers_christmas_carol_png_end[]   asm("_binary_assets_covers_christmas_carol_png_end");
extern "C" const uint8_t _binary_assets_books_time_machine_txt_start[] asm("_binary_assets_books_time_machine_txt_start");
extern "C" const uint8_t _binary_assets_books_time_machine_txt_end[]   asm("_binary_assets_books_time_machine_txt_end");
extern "C" const uint8_t _binary_assets_covers_time_machine_png_start[] asm("_binary_assets_covers_time_machine_png_start");
extern "C" const uint8_t _binary_assets_covers_time_machine_png_end[]   asm("_binary_assets_covers_time_machine_png_end");
extern "C" const uint8_t _binary_assets_books_metamorphosis_txt_start[] asm("_binary_assets_books_metamorphosis_txt_start");
extern "C" const uint8_t _binary_assets_books_metamorphosis_txt_end[]   asm("_binary_assets_books_metamorphosis_txt_end");
extern "C" const uint8_t _binary_assets_covers_metamorphosis_png_start[] asm("_binary_assets_covers_metamorphosis_png_start");
extern "C" const uint8_t _binary_assets_covers_metamorphosis_png_end[]   asm("_binary_assets_covers_metamorphosis_png_end");
extern "C" const uint8_t _binary_assets_books_sherlock_holmes_txt_start[] asm("_binary_assets_books_sherlock_holmes_txt_start");
extern "C" const uint8_t _binary_assets_books_sherlock_holmes_txt_end[]   asm("_binary_assets_books_sherlock_holmes_txt_end");
extern "C" const uint8_t _binary_assets_covers_sherlock_holmes_png_start[] asm("_binary_assets_covers_sherlock_holmes_png_start");
extern "C" const uint8_t _binary_assets_covers_sherlock_holmes_png_end[]   asm("_binary_assets_covers_sherlock_holmes_png_end");
extern "C" const uint8_t _binary_assets_books_the_prophet_txt_start[] asm("_binary_assets_books_the_prophet_txt_start");
extern "C" const uint8_t _binary_assets_books_the_prophet_txt_end[]   asm("_binary_assets_books_the_prophet_txt_end");
extern "C" const uint8_t _binary_assets_covers_the_prophet_png_start[] asm("_binary_assets_covers_the_prophet_png_start");
extern "C" const uint8_t _binary_assets_covers_the_prophet_png_end[]   asm("_binary_assets_covers_the_prophet_png_end");
extern "C" const uint8_t _binary_assets_books_kamizelka_txt_start[] asm("_binary_assets_books_kamizelka_txt_start");
extern "C" const uint8_t _binary_assets_books_kamizelka_txt_end[]   asm("_binary_assets_books_kamizelka_txt_end");
extern "C" const uint8_t _binary_assets_covers_kamizelka_png_start[] asm("_binary_assets_covers_kamizelka_png_start");
extern "C" const uint8_t _binary_assets_covers_kamizelka_png_end[]   asm("_binary_assets_covers_kamizelka_png_end");
extern "C" const uint8_t _binary_assets_books_latarnik_txt_start[] asm("_binary_assets_books_latarnik_txt_start");
extern "C" const uint8_t _binary_assets_books_latarnik_txt_end[]   asm("_binary_assets_books_latarnik_txt_end");
extern "C" const uint8_t _binary_assets_covers_latarnik_png_start[] asm("_binary_assets_covers_latarnik_png_start");
extern "C" const uint8_t _binary_assets_covers_latarnik_png_end[]   asm("_binary_assets_covers_latarnik_png_end");

static const BuiltinBook kBuiltinBooks[] = {
    {"Alice's Adventures in Wonderland", "Lewis Carroll", "Project Gutenberg #11",
     "A girl follows a hurried rabbit down a hole into a world where logic takes the afternoon off.",
     "en", 1865, _binary_assets_books_alice_txt_start, _binary_assets_books_alice_txt_end, _binary_assets_covers_alice_png_start, _binary_assets_covers_alice_png_end},
    {"Frankenstein", "Mary Shelley", "Project Gutenberg #84",
     "A young scientist assembles a living being, then spends the rest of his life answering for it.",
     "en", 1818, _binary_assets_books_frankenstein_txt_start, _binary_assets_books_frankenstein_txt_end, _binary_assets_covers_frankenstein_png_start, _binary_assets_covers_frankenstein_png_end},
    {"A Christmas Carol", "Charles Dickens", "Project Gutenberg #46",
     "Three spirits give a miser one long night to reconsider everything.",
     "en", 1843, _binary_assets_books_christmas_carol_txt_start, _binary_assets_books_christmas_carol_txt_end, _binary_assets_covers_christmas_carol_png_start, _binary_assets_covers_christmas_carol_png_end},
    {"The Time Machine", "H. G. Wells", "Project Gutenberg #35",
     "An inventor travels to the year 802,701 and finds humanity split in two.",
     "en", 1895, _binary_assets_books_time_machine_txt_start, _binary_assets_books_time_machine_txt_end, _binary_assets_covers_time_machine_png_start, _binary_assets_covers_time_machine_png_end},
    {"Metamorphosis", "Franz Kafka", "Project Gutenberg #5200",
     "Gregor Samsa wakes up as an insect. His family adjusts, slowly and badly.",
     "en", 1915, _binary_assets_books_metamorphosis_txt_start, _binary_assets_books_metamorphosis_txt_end, _binary_assets_covers_metamorphosis_png_start, _binary_assets_covers_metamorphosis_png_end},
    {"The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "Project Gutenberg #1661",
     "Twelve cases from Baker Street, told by the friend who was there.",
     "en", 1892, _binary_assets_books_sherlock_holmes_txt_start, _binary_assets_books_sherlock_holmes_txt_end, _binary_assets_covers_sherlock_holmes_png_start, _binary_assets_covers_sherlock_holmes_png_end},
    {"The Prophet", "Kahlil Gibran", "Project Gutenberg #58585",
     "Before sailing home, Almustafa speaks on love, work, joy, sorrow and the rest of it.",
     "en", 1923, _binary_assets_books_the_prophet_txt_start, _binary_assets_books_the_prophet_txt_end, _binary_assets_covers_the_prophet_png_start, _binary_assets_covers_the_prophet_png_end},
    {"Kamizelka", "Bolesław Prus", "Wolne Lektury",
     "Historia pewnej starej kamizelki i dwojga ludzi, którzy oszukiwali się z miłości.",
     "pl", 1882, _binary_assets_books_kamizelka_txt_start, _binary_assets_books_kamizelka_txt_end, _binary_assets_covers_kamizelka_png_start, _binary_assets_covers_kamizelka_png_end},
    {"Latarnik", "Henryk Sienkiewicz", "Wolne Lektury",
     "Stary tułacz znajduje spokój w latarni morskiej, dopóki nie dostaje książki z kraju.",
     "pl", 1881, _binary_assets_books_latarnik_txt_start, _binary_assets_books_latarnik_txt_end, _binary_assets_covers_latarnik_png_start, _binary_assets_covers_latarnik_png_end},
};
static const size_t kBuiltinBookCount = sizeof(kBuiltinBooks) / sizeof(kBuiltinBooks[0]);
